### ISSUE TITLE
Character appear slow and delayed when typing

### ISSUE THREAD

**Issue by imshuffling** [davidfateh/repeater-app#5]
Hey @davidfateh I Installed the repeater app from the app store.
https://user-images.githubusercontent.com/739061/133297218-6f7fafc5-903c-49e9-945f-e3dc569bcb5e.mov

Digging into the code uncommenting `onChange={createOnChangeHandler(item, 'value')}` fixes this but obviously wont save the value.

I'm using the latest Firefox on Mac.

**Comment by davidfateh** [comment]
Hey @imshuffling, I will look into this today. Your video does seem like a pretty bad bug.

**Comment by imshuffling** [comment]
Thanks @davidfateh

**Comment by davidfateh** [comment]
Hey @imshuffling

I wasn't able to reproduce this on a production site with a JSON field. Mine seemed to work fine. Are you running this app locally or have you installed this via the marketplace?

**Comment by imshuffling** [comment]
Hey @davidfateh , Thanks for looking into it. I'm running the repeater app from the Contentful store. I've just tested it in the latest Chrome on mac and its working fine. It's just seems to be Firefox.

![image](https://user-images.githubusercontent.com/739061/133760511-fa26e1ef-23a7-4e31-b782-1f1f37713063.png)
